language: cpp
before_install:
  - sudo apt-add-repository -y ppa:anatol/tup
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository -y ppa:sao/backports
  - sudo apt-add-repository -y ppa:fcitx-team/nightly
  - sudo apt-add-repository -y ppa:asolovets/backports
  - sudo add-apt-repository ppa:apokluda/boost1.53 --yes
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.2.1/bazel-0.2.1-jdk7-installer-linux-x86_64.sh'
  - chmod +x bazel-0.2.1-jdk7-installer-linux-x86_64.sh
  - ./bazel-0.2.1-jdk7-installer-linux-x86_64.sh --user
  - wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1204/x86_64/cuda-repo-ubuntu1204_7.0-28_amd64.deb
  - sudo dpkg -i cuda-repo-ubuntu1204_7.0-28_amd64.deb
  - git submodule update --init
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-numpy swig python-dev libgflags-dev libgoogle-glog-dev libboost1.53-all-dev g++-4.9 tup cuda && sudo ldconfig
install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 99
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 99
  - g++ --version

before_script:
  - export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH=/usr/local/cuda/nvvm/lib64:$LD_LIBRARY_PATH
  - export PATH=/usr/local/cuda/bin:$PATH
script:
  - cat input | ./configure
  - bazel test tensorflow/contrib/warpctc:all --test_output=all --copt=-DCTC_DISABLE_OMP --define CI=true --copt=-I/usr/local/lib/python2.7/dist-packages/numpy/core/include/
  - cd /usr/local/lib
  - ls
  - cd python2.7
  - ls
  - cd dist-packages
  - ls
  - cd numpy
  - ls
  - cd core
  - ls
  - cd include
  - ls
